name: 'Install samo build utility'
description: 'Samo build and release project, helm and docker utility.'
author: 'andrejpetras'
branding:
  icon: edit
  color: blue
inputs:
  version:
    description: 'Version of the samo build utility'
    required: false
    default: '3.15.0'
  os:
    description: 'Binary os (Darwin,Linux,Windows)'
    required: false
    default: 'Linux'    
  platform:
    description: 'Binary platform (amr64,i386,x86_64)'
    required: false
    default: 'x86_64'    
  download_url:
    description: 'Download samo URL template.'
    required: false
    default: 'https://github.com/lorislab/samo/releases/download/${version}/samo_${os}_${platform}.tar.gz'
outputs: {}
runs:
  using: 'node20'
  main: 'dist/index.js'
